export enum BranchLogisticsStatus {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  RECEIVED_AT_SENDER_WAREHOUSE = 'RECEIVED_AT_SENDER_WAREHOUSE',
  IN_TRANSIT = 'IN_TRANSIT',
  RECEIVED_AT_RECEIVER_WAREHOUSE = 'RECEIVED_AT_RECEIVER_WAREHOUSE',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
